// <auto-generated />
using LibreriaDefinitiva.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibreriaDefinitiva.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibreriaDefinitiva.Models.Libro", b =>
                {
                    b.Property<string>("Isbn")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Autore")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edizione")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ScaffaleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Titolo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Isbn");

                    b.HasIndex("ScaffaleId");

                    b.ToTable("Libro");
                });

            modelBuilder.Entity("LibreriaDefinitiva.Models.Scaffale", b =>
                {
                    b.Property<string>("ScaffaleId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Genere")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ScaffaleId");

                    b.ToTable("Libreria");
                });

            modelBuilder.Entity("LibreriaDefinitiva.Models.Libro", b =>
                {
                    b.HasOne("LibreriaDefinitiva.Models.Scaffale", "Scaffale")
                        .WithMany("ScaffaleDiLibri")
                        .HasForeignKey("ScaffaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scaffale");
                });

            modelBuilder.Entity("LibreriaDefinitiva.Models.Scaffale", b =>
                {
                    b.Navigation("ScaffaleDiLibri");
                });
#pragma warning restore 612, 618
        }
    }
}
